script:
  - git remote add gigalixir https://rsp.1990%40yandex.ru:9e9c8970-c2d4-4756-944d-913dd3764755@git.gigalixir.com/unwitting-indolent-pondskater.git
  - mix test && git push -f gigalixir HEAD:refs/heads/master
language: elixir
elixir: 1.6.2
otp_release: 20.2.4