env:
  - MIX_ENV=test
script:
  - git remote add gigalixir https://$GIGALIXIR_EMAIL:$GIGALIXIR_API_KEY@git.gigalixir.com/$GIGALIXIR_APP_NAME.git
  - mix coveralls.travis && mix credo && git push -f gigalixir HEAD:refs/heads/master
  
language: elixir
elixir: 1.6.2
otp_release: 20.2.4

